"""Launcher application seam contracts and workflow catalog."""

from .contracts import LauncherIntent, LauncherStateSnapshot
from .services import (
    connector_backend_available,
    execute_connector_action,
    fetch_connector_inventory,
    fetch_workspace_connector_inventory,
    is_valid_repair_token,
    save_workspace_connector_binding,
)
from .state_builder import build_launcher_state_snapshot, build_windows_ops_plan
from .windows_ops import (
    WindowsOpsChainStep,
    WindowsOpsExecutionKind,
    WindowsOpsPlan,
    build_windows_ops_descriptor,
    build_windows_ops_plan_payload,
)
from .terminal_recipes import (
    TERMINAL_RECIPE_MARKER,
    TerminalRecipeMarkerResult,
    TerminalRecipePlan,
    apply_terminal_recipe_marker,
    build_tracked_terminal_recipe,
    build_tracked_recipe,
    handle_recipe_marker,
    recipe_marker,
)
from .embedded_terminal import EmbeddedTerminalSession, TerminalSessionUpdate
from .connector_dispatch import (
    connector_action_http_payload,
    connector_action_record,
    connector_action_status_label,
    execute_guided_connector_setup,
    missing_secret_record,
)
from .connector_workflow import (
    apply_connector_action_feedback,
    drain_connector_action_events,
    handle_connector_action_request,
    handle_connector_guided_link_request,
    perform_connector_action_request,
    run_connector_action_request,
    save_instance_connector_binding,
    save_instance_governance,
    start_connector_action_async,
    start_connector_guided_link_async,
)
from .workflow_panel import (
    WorkflowPanelState,
    build_workflow_loaded_state,
    build_workflow_panel_state,
    build_workflow_queued_state,
    resolve_workflow_loop_spec,
    workflow_command_strings,
)
from .windows_ops_presenter import (
    WindowsOpsPanelState,
    apply_windows_ops_feedback,
    artifact_display_path,
    build_windows_gate_followup_line,
    build_windows_handoff_line,
    build_windows_ops_panel_state,
    release_gate_is_green,
)
from .windows_ops_runtime import (
    beta_release_dry_run_report_path,
    build_windows_release_receipt_payload,
    collect_windows_service_snapshot,
    default_windows_ops_event_id,
    latest_runtime_artifact,
    preferred_package_output,
    release_dry_run_gate_details,
    release_review_order,
    repo_python_path,
    run_repo_python,
    snapshot_file_signature,
    summarize_release_dry_run_report,
    windows_ops_artifact_refs,
    windows_service_snapshot_changes,
    write_windows_release_receipt,
    write_windows_release_summary,
)
from .windows_ops_guidance import (
    summarize_windows_recipe_result,
    windows_ops_chain_changes,
    windows_ops_guidance,
)
from .windows_ops_state import (
    WindowsOpsChainResult,
    advance_windows_ops_chain,
    build_windows_ops_feedback_kwargs,
    build_windows_ops_state_payload,
    normalize_windows_gate_details,
    normalize_windows_gate_recommendation_details,
    normalize_windows_ops_artifacts,
    start_windows_ops_chain,
)
from .instance_manager_presenter import (
    ConnectorBindingSaveRequest,
    ConnectorBindingState,
    GovernanceSaveRequest,
    GovernanceEditorState,
    InstanceManagerState,
    RolePreset,
    SelectorOption,
    SectionToggleState,
    WorkspaceCreateRequest,
    build_connector_binding_editor_state,
    build_connector_binding_feedback,
    build_connector_binding_save_request,
    build_governance_editor_state,
    build_governance_save_request,
    build_instance_manager_state,
    build_section_toggle_state,
    build_workspace_create_request,
    build_workspace_create_copy,
    connector_history_line,
    parse_policy_lines,
    role_preset,
    selector_label,
    workspace_collaboration_hint,
    workspace_default_purpose,
    workspace_example_names,
    workspace_first_run_recipe,
    workspace_recent_context,
    workspace_reentry_hint,
    workspace_role_label,
    workspace_role_summary,
    workspace_saved_context,
    workspace_onboarding_ready_message,
)
from .workspace_state import enabled_workspace_names, resolve_active_instance_payload
from .workflows import WorkflowCommand, WorkflowSpec, get_workflow_spec, list_workflow_specs
from .library_workflow import (
    LibraryWorkflowController,
    LibraryChatSubmission,
    apply_library_payload,
    build_library_chat_submission,
    compose_library_aware_message,
    sync_assistant_library_context,
)
from .workspace_activation import (
    apply_instance_switch as apply_workspace_instance_switch,
    bootstrap_instance_switcher as bootstrap_workspace_instance_switcher,
    complete_bootstrap_instance_switcher as complete_bootstrap_workspace_instance_switcher,
    select_active_instance as select_workspace_instance,
)
from .workspace_mutation import (
    delete_workspace as delete_workspace_instance,
    refresh_instance_manager as refresh_workspace_instance_manager,
    save_workspace as save_workspace_instance,
)
from .workspace_refresh import (
    load_instance_logs as load_workspace_instance_logs,
    refresh_instance_views as refresh_workspace_instance_views,
)
from .shell_status import (
    set_daily_activity,
    sync_right_tray,
    update_route_preview,
)

__all__ = [
    "LauncherIntent",
    "LauncherStateSnapshot",
    "connector_backend_available",
    "execute_connector_action",
    "fetch_connector_inventory",
    "fetch_workspace_connector_inventory",
    "is_valid_repair_token",
    "save_workspace_connector_binding",
    "build_launcher_state_snapshot",
    "build_windows_ops_plan",
    "WindowsOpsChainStep",
    "WindowsOpsExecutionKind",
    "WindowsOpsPlan",
    "build_windows_ops_descriptor",
    "build_windows_ops_plan_payload",
    "TERMINAL_RECIPE_MARKER",
    "TerminalRecipeMarkerResult",
    "TerminalRecipePlan",
    "EmbeddedTerminalSession",
    "TerminalSessionUpdate",
    "recipe_marker",
    "build_tracked_terminal_recipe",
    "build_tracked_recipe",
    "apply_terminal_recipe_marker",
    "handle_recipe_marker",
    "connector_action_http_payload",
    "connector_action_record",
    "connector_action_status_label",
    "execute_guided_connector_setup",
    "missing_secret_record",
    "save_instance_governance",
    "save_instance_connector_binding",
    "perform_connector_action_request",
    "apply_connector_action_feedback",
    "run_connector_action_request",
    "start_connector_action_async",
    "start_connector_guided_link_async",
    "drain_connector_action_events",
    "handle_connector_action_request",
    "handle_connector_guided_link_request",
    "WorkflowPanelState",
    "build_workflow_loaded_state",
    "build_workflow_panel_state",
    "build_workflow_queued_state",
    "resolve_workflow_loop_spec",
    "workflow_command_strings",
    "WindowsOpsPanelState",
    "apply_windows_ops_feedback",
    "artifact_display_path",
    "build_windows_gate_followup_line",
    "build_windows_handoff_line",
    "build_windows_ops_panel_state",
    "release_gate_is_green",
    "beta_release_dry_run_report_path",
    "build_windows_release_receipt_payload",
    "collect_windows_service_snapshot",
    "default_windows_ops_event_id",
    "latest_runtime_artifact",
    "preferred_package_output",
    "release_dry_run_gate_details",
    "release_review_order",
    "repo_python_path",
    "run_repo_python",
    "snapshot_file_signature",
    "summarize_release_dry_run_report",
    "summarize_windows_recipe_result",
    "windows_ops_artifact_refs",
    "windows_ops_chain_changes",
    "windows_ops_guidance",
    "windows_service_snapshot_changes",
    "WindowsOpsChainResult",
    "advance_windows_ops_chain",
    "build_windows_ops_feedback_kwargs",
    "build_windows_ops_state_payload",
    "normalize_windows_gate_details",
    "normalize_windows_gate_recommendation_details",
    "normalize_windows_ops_artifacts",
    "start_windows_ops_chain",
    "ConnectorBindingSaveRequest",
    "ConnectorBindingState",
    "GovernanceSaveRequest",
    "GovernanceEditorState",
    "InstanceManagerState",
    "RolePreset",
    "SectionToggleState",
    "SelectorOption",
    "WorkspaceCreateRequest",
    "build_connector_binding_editor_state",
    "build_connector_binding_feedback",
    "build_connector_binding_save_request",
    "build_governance_editor_state",
    "build_governance_save_request",
    "build_instance_manager_state",
    "build_section_toggle_state",
    "build_workspace_create_request",
    "build_workspace_create_copy",
    "connector_history_line",
    "parse_policy_lines",
    "role_preset",
    "selector_label",
    "workspace_collaboration_hint",
    "workspace_default_purpose",
    "workspace_example_names",
    "workspace_first_run_recipe",
    "workspace_recent_context",
    "workspace_reentry_hint",
    "workspace_role_label",
    "workspace_role_summary",
    "workspace_saved_context",
    "workspace_onboarding_ready_message",
    "write_windows_release_receipt",
    "write_windows_release_summary",
    "enabled_workspace_names",
    "resolve_active_instance_payload",
    "LibraryWorkflowController",
    "LibraryChatSubmission",
    "apply_library_payload",
    "build_library_chat_submission",
    "compose_library_aware_message",
    "sync_assistant_library_context",
    "apply_workspace_instance_switch",
    "bootstrap_workspace_instance_switcher",
    "complete_bootstrap_workspace_instance_switcher",
    "select_workspace_instance",
    "save_workspace_instance",
    "delete_workspace_instance",
    "refresh_workspace_instance_manager",
    "load_workspace_instance_logs",
    "refresh_workspace_instance_views",
    "set_daily_activity",
    "sync_right_tray",
    "update_route_preview",
    "WorkflowCommand",
    "WorkflowSpec",
    "get_workflow_spec",
    "list_workflow_specs",
]
